# Generated by Django 3.2.12 on 2022-06-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_entry_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
